demosite = "https://willfaught.com/paige"
description = "Powerful, pliable pixel perfection. An advanced Hugo theme."
features = [
  "accessibility",
  "blog",
  "bootstrap",
  "customizable",
  "facebook sharing",
  "google analytics",
  "header links",
  "landing page",
  "light color scheme",
  "math typesetting",
  "menus",
  "minimal design",
  "responsive",
  "safari and firefox reader view",
  "search",
  "sections",
  "seo",
  "single column",
  "social links",
  "twitter sharing"
]
homepage = "https://github.com/willfaught/paige"
license = "MIT"
licenselink = "https://github.com/willfaught/paige/blob/master/LICENSE"
name = "Paige"
tags = [
  "blog",
  "bootstrap",
  "contact",
  "dark",
  "dark mode",
  "gallery",
  "hero",
  "landing",
  "light",
  "minimal",
  "multilingual",
  "personal",
  "portfolio",
  "responsive"
]

[author]
homepage = "https://willfaught.com"
name = "Will Faught"
