baseurl: https://willfaught.com
copyright: Â© Will Faught
enablerobotstxt: true
languagecode: en-us
languages:
  en:
    menu:
      main:
      - identifier: home
        name: Home
        url: /
        weight: 10
      - identifier: content
        name: Content
        url: /content/
        weight: 20
      - identifier: layouts
        name: Layouts
        url: /layouts/
        weight: 30
      - identifier: shortcodes
        name: Shortcodes
        url: /shortcodes/
        weight: 40
      - identifier: categories
        name: Categories
        url: /categories/
        weight: 50
      - identifier: tags
        name: Tags
        url: /tags/
        weight: 60
      - identifier: search
        name: Search
        url: /search/
        weight: 70
    weight: 10
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noclasses: false
  tableofcontents:
    endlevel: 6
    ordered: true
    startlevel: 2
outputs:
  home:
  - html
  - json
  - rss
paginate: 50
params:
  authors:
    michael_bluth:
      name: Michael Bluth
social:
  twitter: username
theme: paige
timezone: America/Los_Angeles
titlecasestyle: Go
