baseurl: https://example.com
copyright: Â© Michael Bluth
enablerobotstxt: true
languagecode: en-us
languages:
  en:
    menu:
      main:
      - identifier: home
        name: Home
        url: /
        weight: 10
      - identifier: about
        name: About
        url: /about/
        weight: 20
      - identifier: blog
        name: Blog
        url: /blog/
        weight: 30
      - identifier: categories
        name: Categories
        url: /categories/
        weight: 40
      - identifier: tags
        name: Tags
        url: /tags/
        weight: 50
      - identifier: search
        name: Search
        url: /search/
        weight: 60
    title: No Borders, No Limits
    weight: 10
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noclasses: false
  tableofcontents:
    endlevel: 6
    ordered: true
    startlevel: 2
outputs:
  home:
  - html
  - json
  - rss
paginate: 50
params:
  paige:
    social:
      discord:
        bootstrap_icon: discord
        name: Discord
        url: https://discord.com/users/username
      dribbble:
        bootstrap_icon: dribbble
        name: Dribbble
        url: https://dribbble.com/username
      email:
        bootstrap_icon: envelope
        name: E-mail
        url: mailto:username@example.com
      facebook:
        bootstrap_icon: facebook
        name: Facebook
        url: https://facebook.com/username
      github:
        bootstrap_icon: github
        name: GitHub
        url: https://github.com/username
      instagram:
        bootstrap_icon: instagram
        name: Instagram
        url: https://instagram.com/username
      linkedin:
        bootstrap_icon: linkedin
        name: LinkedIn
        url: https://linkedin.com/in/username
      medium:
        bootstrap_icon: medium
        name: Medium
        url: https://medium.com/@username
      pinterest:
        bootstrap_icon: pinterest
        name: Pinterest
        url: https://pinterest.com/username
      quora:
        bootstrap_icon: quora
        name: Quora
        url: https://quora.com/profile/username
      reddit:
        bootstrap_icon: reddit
        name: Reddit
        url: https://reddit.com/u/username
      spotify:
        bootstrap_icon: spotify
        name: Spotify
        url: https://open.spotify.com/user/username
      stackoverflow:
        bootstrap_icon: stack-overflow
        name: Stack Overflow
        url: https://stackoverflow.com/users/username
      strava:
        bootstrap_icon: strava
        name: Strava
        url: https://strava.com/athletes/username
      twitch:
        bootstrap_icon: twitch
        name: Twitch
        url: https://twitch.tv/username
      twitter:
        bootstrap_icon: twitter
        name: Twitter
        url: https://twitter.com/username
      vimeo:
        bootstrap_icon: vimeo
        name: Vimeo
        url: https://vimeo.com/username
      wordpress:
        bootstrap_icon: wordpress
        name: Wordpress
        url: https://username.wordpress.com
      yelp:
        bootstrap_icon: yelp
        name: Yelp
        url: https://yelp.com/user_details?userid=username
      youtube:
        bootstrap_icon: youtube
        name: YouTube
        url: https://youtube.com/user/username
permalinks:
  blog: /blog/:year/:month/:day/:title/
social:
  twitter: username
theme: paige
timezone: America/Los_Angeles
titlecasestyle: Go
