baseurl = "https://example.com"
copyright = "Â© Will Faught"
enablerobotstxt = true
languagecode = "en-us"
paginate = 50
timezone = "America/Los_Angeles"
titlecasestyle = "Go"

[languages.en]
title = "Paige"
weight = 10

[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[languages.en.menu.main]]
identifier = "content"
name = "Content"
url = "/content/"
weight = 20

[[languages.en.menu.main]]
identifier = "layouts"
name = "Layouts"
url = "/layouts/"
weight = 30

[[languages.en.menu.main]]
identifier = "shortcodes"
name = "Shortcodes"
url = "/shortcodes/"
weight = 40

[[languages.en.menu.main]]
identifier = "customization"
name = "Customization"
url = "/customization/"
weight = 50

[[languages.en.menu.main]]
identifier = "authors"
name = "Authors"
url = "/authors/"
weight = 60

[[languages.en.menu.main]]
identifier = "series"
name = "Series"
url = "/series/"
weight = 70

[[languages.en.menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 80

[[languages.en.menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 90

[[languages.en.menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 100

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noclasses = false

[markup.tableofcontents]
endlevel = 6
ordered = true
startlevel = 2

[[module.imports]]
path = "github.com/willfaught/paige"

[outputs]
home = ["atom", "html", "json", "rss"]
section = ["atom", "html", "rss"]
taxonomy = ["atom", "html", "rss"]
term = ["atom", "html", "rss"]

[params.authors.will-faught]
default = true
email = "will.faught@example.com"
name = "Will Faught"
url = "https://willfaught.com/paige"

[params.paige.git]
commit_url = "https://github.com/willfaught/paige/commit/%s"

[[params.paige.feed.atom.authors]]
email = "will.faught@example.com"
name = "Will Faught"
url = "https://willfaught.com/paige"

[params.paige.feed.rss]
managing_editor = "will.faught@example.com (Will Faught)"
web_master = "will.faught@example.com (Will Faught)"

[params.paige.file_link]
content = "Edit this page"
disable = true
url = "https://github.com/willfaught/paige/edit/master/exampleSite/content/%s"

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"
